version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: portfolio-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio-backend
    restart: unless-stopped
    environment:
      - PORT=5001
      - MONGODB_URI=mongodb://mongo:27017/portfolio
      - NODE_ENV=development
    ports:
      - "5002:5001"
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:5002/api
    container_name: portfolio-frontend
    restart: unless-stopped
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:


