version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: portfolio-mongo-prod
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=your_secure_password_here
    networks:
      - portfolio-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio-backend-prod
    restart: unless-stopped
    environment:
      - PORT=5001
      - MONGODB_URI=mongodb://admin:your_secure_password_here@mongo:27017/portfolio?authSource=admin
      - NODE_ENV=production
    networks:
      - portfolio-network
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: /api
    container_name: portfolio-frontend-prod
    restart: unless-stopped
    environment:
      - PORT=3000
    networks:
      - portfolio-network
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: portfolio-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - portfolio-network
    depends_on:
      - frontend
      - backend

volumes:
  mongo_data:

networks:
  portfolio-network:
    driver: bridge
